/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LabRouteImport } from './routes/lab'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserUsernameRouteImport } from './routes/user/$username'
import { Route as TvSlugRouteImport } from './routes/tv/$slug'
import { Route as MovieSlugRouteImport } from './routes/movie/$slug'
import { Route as MangaSlugRouteImport } from './routes/manga/$slug'
import { Route as GameSlugRouteImport } from './routes/game/$slug'
import { Route as BookSlugRouteImport } from './routes/book/$slug'
import { Route as AnimeSlugRouteImport } from './routes/anime/$slug'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'

const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUsernameRoute = UserUsernameRouteImport.update({
  id: '/user/$username',
  path: '/user/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const TvSlugRoute = TvSlugRouteImport.update({
  id: '/tv/$slug',
  path: '/tv/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieSlugRoute = MovieSlugRouteImport.update({
  id: '/movie/$slug',
  path: '/movie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MangaSlugRoute = MangaSlugRouteImport.update({
  id: '/manga/$slug',
  path: '/manga/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GameSlugRoute = GameSlugRouteImport.update({
  id: '/game/$slug',
  path: '/game/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeSlugRoute = AnimeSlugRouteImport.update({
  id: '/anime/$slug',
  path: '/anime/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/lab': typeof LabRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/anime/$slug': typeof AnimeSlugRoute
  '/book/$slug': typeof BookSlugRoute
  '/game/$slug': typeof GameSlugRoute
  '/manga/$slug': typeof MangaSlugRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/tv/$slug': typeof TvSlugRoute
  '/user/$username': typeof UserUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/lab': typeof LabRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/anime/$slug': typeof AnimeSlugRoute
  '/book/$slug': typeof BookSlugRoute
  '/game/$slug': typeof GameSlugRoute
  '/manga/$slug': typeof MangaSlugRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/tv/$slug': typeof TvSlugRoute
  '/user/$username': typeof UserUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/feed': typeof FeedRoute
  '/lab': typeof LabRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/anime/$slug': typeof AnimeSlugRoute
  '/book/$slug': typeof BookSlugRoute
  '/game/$slug': typeof GameSlugRoute
  '/manga/$slug': typeof MangaSlugRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/tv/$slug': typeof TvSlugRoute
  '/user/$username': typeof UserUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feed'
    | '/lab'
    | '/settings'
    | '/anime/$slug'
    | '/book/$slug'
    | '/game/$slug'
    | '/manga/$slug'
    | '/movie/$slug'
    | '/tv/$slug'
    | '/user/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feed'
    | '/lab'
    | '/settings'
    | '/anime/$slug'
    | '/book/$slug'
    | '/game/$slug'
    | '/manga/$slug'
    | '/movie/$slug'
    | '/tv/$slug'
    | '/user/$username'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/feed'
    | '/lab'
    | '/_authenticated/settings'
    | '/anime/$slug'
    | '/book/$slug'
    | '/game/$slug'
    | '/manga/$slug'
    | '/movie/$slug'
    | '/tv/$slug'
    | '/user/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  FeedRoute: typeof FeedRoute
  LabRoute: typeof LabRoute
  AnimeSlugRoute: typeof AnimeSlugRoute
  BookSlugRoute: typeof BookSlugRoute
  GameSlugRoute: typeof GameSlugRoute
  MangaSlugRoute: typeof MangaSlugRoute
  MovieSlugRoute: typeof MovieSlugRoute
  TvSlugRoute: typeof TvSlugRoute
  UserUsernameRoute: typeof UserUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$username': {
      id: '/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof UserUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$slug': {
      id: '/tv/$slug'
      path: '/tv/$slug'
      fullPath: '/tv/$slug'
      preLoaderRoute: typeof TvSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$slug': {
      id: '/movie/$slug'
      path: '/movie/$slug'
      fullPath: '/movie/$slug'
      preLoaderRoute: typeof MovieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manga/$slug': {
      id: '/manga/$slug'
      path: '/manga/$slug'
      fullPath: '/manga/$slug'
      preLoaderRoute: typeof MangaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$slug': {
      id: '/game/$slug'
      path: '/game/$slug'
      fullPath: '/game/$slug'
      preLoaderRoute: typeof GameSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$slug': {
      id: '/anime/$slug'
      path: '/anime/$slug'
      fullPath: '/anime/$slug'
      preLoaderRoute: typeof AnimeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  FeedRoute: FeedRoute,
  LabRoute: LabRoute,
  AnimeSlugRoute: AnimeSlugRoute,
  BookSlugRoute: BookSlugRoute,
  GameSlugRoute: GameSlugRoute,
  MangaSlugRoute: MangaSlugRoute,
  MovieSlugRoute: MovieSlugRoute,
  TvSlugRoute: TvSlugRoute,
  UserUsernameRoute: UserUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
